#
#    ___  _    ____ _   _ ____ ____ ____ ____ _  _ _  _ ____
#    |__] |    |__|  \_/  |___ |__/ |__/ |__| |\ | |_/  [__
#    |    |___ |  |   |   |___ |  \ |  \ |  | | \| | \_ ___]    v1.0.4 by cyne
#

update_notification: true

use_chat_format: true

#The higher the priority, the higher the rank is displayed in the tablist.
ranks:
  default:
    prefix: '&aPlayer &8● &7'
    suffix: ''
    chat_format: '&8┃ &aPlayer &8● &7%player% &8» &r%message%'
    priority: 1
    default: true
  admin:
    prefix: '&4Admin &8● &7'
    suffix: ''
    chat_format: '&8┃ &4Admin &8● &7%player% &8» &r%message%'
    priority: 2
    default: false